### ISSUE TITLE
多次运行中key不变

### ISSUE THREAD

**Issue by YoshieraHuang** [gwuhaolin/livego#117]
在livego中，对channel生成key的时候使用的是golang的rand包。在golang中rand包生成的是伪随机数，每次运行的seed是不变的。所以虽然在每次运行中各个channel的key不会重复，但是对于多次运行中生成的key是不变的。比如说，第一次运行的时候，第一次生成的key是`key1`，第二次生成的key是`key2`，那在第二次运行程序的时候，第一次生成的key肯定也是`key1`，第二次生成的key肯定也是`key2`。我们可以在uid的包里面添加一个设置rand的seed的init函数来解决这个问题：
```go
func init() {
	// rand.Intn is pseudo-random, set seed to make it vary
	rand.Seed(time.Now().UnixNano())
}
```

**Comment by DKingCN** [comment]
https://github.com/gwuhaolin/livego/commit/d875076f9753616b40288bc2c709aefa7d04f4ce#r40368823
