### ISSUE TITLE
直播流不带声音，flv_archive保存的flv文件格式不对，无法播放

### ISSUE THREAD

**Issue by dalaogan** [gwuhaolin/livego#164]
大疆无人机推送的直播流是不带声音的。此时打开flv_archive选项保存视频。

**Comment by 3xxx** [comment]
找到原因没有啊

**Comment by dalaogan** [comment]
没。不熟悉go语言，换成了[Node-Media-Server](https://github.com/illuspas/Node-Media-Server)来实现直播。
