### ISSUE TITLE
大佬请问下开发流媒体服务需要哪些基础

### ISSUE THREAD

**Issue by SpringStudent** [gwuhaolin/livego#193]
有哪些推荐的书籍或者教程可以参考下嘛

**Comment by loustrong** [comment]
同问。

**Comment by CarsonSlovoka** [comment]
README文件「和 flv.js 搭配使用」
> https://github.com/gwuhaolin/livego/blob/150d08fdd6baff0797c0a7b55f0c9d4c008a2c83/README_cn.md#%E5%92%8C-flvjs-%E6%90%AD%E9%85%8D%E4%BD%BF%E7%94%A8

可以幫您連結到

> [音视频技术参考资料](https://github.com/gwuhaolin/blog/issues/5)

**Comment by matthewgao** [comment]
not a issue
