### ISSUE TITLE
HandshakeServer err

### ISSUE THREAD

**Issue by joastonish** [gwuhaolin/livego#2]
直接用控制台ffmpeg推送是好的。写代码起进程启动ffmpeg推送就报handleConn HandshakeServer err：rtmp：handshake version= 80 invalid。。请问何解

**Comment by joastonish** [comment]
啪啪打脸。。推到http去了。又是一个冲动的问题。。作者可以继续忽略。。谁能告诉我怎么关闭！！！！太丢人了

**Comment by gwuhaolin** [comment]
这是从生疏到熟练的经历，加油！
