### ISSUE TITLE
可以推多路rtmp流吗？

### ISSUE THREAD

**Issue by gengwb** [gwuhaolin/livego#201]

**Comment by ykk648** [comment]
`server:
- appname: live
  live: true
  hls: true
  api: true
  flv: true
- appname: ttt1
  live: true
  hls: true
  api: true
  flv: true
- appname: ttt2
  live: true
  hls: true
  api: true
  flv: true
- appname: ttt3
  live: true
  hls: true
  api: true
  flv: true
- appname: ttt0
  live: true
  hls: true
  api: true
  flv: true`

**Comment by matthewgao** [comment]
肯定可以呢，指的是上面回复的多app么？
