### ISSUE TITLE
你好，如何让局域网能访问

### ISSUE THREAD

**Issue by zhuCheer** [gwuhaolin/livego#22]
我这配置好后只能向127.0.0.1的本地推流，局域网推不成功，可能是什么原因呢？

**Comment by 3eat** [comment]
默认的Windows 10 网络配置可以推流。如果你处于公司的复杂网络中，多半是因为防火墙或者交换机配置的原因。
The default Windows 10 network configuration is ok. If you're in a company's  workgroup network, it's most likely because of a firewall or switch configuration problem.
