### ISSUE TITLE
该项目的代码很大部分和我的相似，虽然我不在维护，但作者直接拿来用是不是不太好？

### ISSUE THREAD

**Issue by sheepbao** [gwuhaolin/livego#28]
https://github.com/sheepbao/sms/tree/master/src/vendor/sheepbao.com/media

**Comment by jinleileiking** [comment]
hehe.....

**Comment by sheepbao** [comment]
@jinleileiking 你是作者吗？

**Comment by sheepbao** [comment]
反正我也不维护了，发这个issuse也不期望啥，希望作者说一下参考而已，不信你可以看这个项目的第一次提交的文件，和我的一模一样，我一些没有实现的kcp-ts，dash等都一模一样。

**Comment by runner365** [comment]
@sheepbao 昨天刚有网友跟我说了这个代码的来源，我以前确实不知道，这个是我fork出来的代码地址: https://github.com/runner365/livego<br/>
我在readme上面加上你代码的连接。不过我fork出来的库增加了很多功能:
* http flv静态拉流
* rtmp动态拉流
* rtmp动态推流
* rtmp流状态
* rtmp静态拉流
* rtmp静态推流
* 云导播台 多流切播。<br/>

也优化了性能，原代理里面有不少性能的坑，已经优化了。<br/>
谢谢你的源码，我在我的readme.md中标注你的代码地址。

**Comment by brownchow** [comment]
感觉可以加个 inspried by...
