### ISSUE TITLE
ffmpeg 音频推流到livego失败

### ISSUE THREAD

**Issue by andarm** [gwuhaolin/livego#37]
### 使用ffmpeg进行推流 
- ffmpeg -re -i audio\3.mp3 -acodec copy -vcodec copy -vn -f flv -y  rtmp://localhost:1935/live/movie 
- 问题： 出现下面的提示 
![image](https://user-images.githubusercontent.com/14047502/42934867-d38876b0-8b7a-11e8-9d18-5501d89a910e.png)

**Comment by mymmsc** [comment]
me too

**Comment by aute** [comment]
参考一下这个：
`ffmpeg  -i  rtmp://live.hkstv.hk.lxdns.com/live/hks  -acodec  copy  -vcodec  copy  -f  flv  rtmp://0.0.0.0:1935/hks/http`
