### ISSUE TITLE
livego是否有大规模使用-性能如何

### ISSUE THREAD

**Issue by ancin** [gwuhaolin/livego#42]
性能如何，各位网友是否有试验过。

**Comment by fanr520** [comment]
BUG比较多 要拿回来自己测试，我修改了很多地方的BUG

**Comment by hackfengJam** [comment]
@fanr520 老哥，改的bug 要不发 pull request ，让作者改一下=。=?

**Comment by matthewgao** [comment]
单纯推rtmp 不写flv和hls的前提 经过我的改进性能已经高于nginx-rtmp-module 在单纯rtmp配置下的性能
