### ISSUE TITLE
关于性能问题，求助

### ISSUE THREAD

**Issue by runner365** [gwuhaolin/livego#5]
你好，首先多谢贡献这么好的rtmp server开源。
近期我用SRS_bench对livego做性能测试，测试的设备是阿里16核的服务器。
并发publish 300路rtmp流到livego， CPU占用率比较高。
其中一个原因是内部的报文传递，都直接用的内存copy，而不是应用，导致cpu比较高。
我对大部分的接口进行了修改：
type WriteCloser interface {
	Closer
	Alive
	CalcTime
	Write(Packet) error------>Write(*Packet) error
}

type VirWriter struct {
	Uid         string
	closed      bool
	av.RWBaser
	conn        StreamReadWriteCloser
	packetQueue chan av.Packet------>packetQueue chan *av.Packet
}
等等，就不贴所有代码了，主要就是用引用传递，而不是每次都做copy。
修改后cpu占用率降下来不少。

但是目前在300路rtmp publish并发的情况下，CPU占用率还是比较高，50%左右。
定位了一下，主要cpu消耗较多的是下面这个部分：
func (s *Stream) TransStart() {
        .......
	for {
               ......
		err := s.r.Read(&p)
                ......
               **_//Start: 从这里开始的gop cache的处理，cpu消耗非常大！，如果注释掉这部分，性能和SRS rtmp服务器性能差不多_**
                s.cache.Write(p)

		for item := range s.ws.IterBuffered() {
			v := item.Val.(*PackWriterCloser)
			if !v.init {
				if err = s.cache.Send(v.w); err != nil {
					log.Printf("[%s] send cache packet error: %v, remove", v.w.Info(), err)
					s.ws.Remove(item.Key)
					continue
				}
				v.init = true
			} else {
				new_packet := p
				if err = v.w.Write(&new_packet); err != nil {
					log.Printf("[%s] write packet error: %v, remove", v.w.Info(), err)
					s.ws.Remove(item.Key)
				}
			}
                        //End: 到这里结束
		}
希望能帮助看看gop cache这部分怎么优化，如果方便，是否能qq交流。这是我的邮箱: xiaoq_bj@126.com。

**Comment by gwuhaolin** [comment]
如果有好的意见欢迎提merge，我最近业务需求繁忙可能暂时没有时间来优化它。
我选择开源就是希望大家都可以来一起提升它。
注意这个项目还不能用于生产环境，只是我的一个试验品还不成熟。
可以直接在github上讨论，这样的好处是大家都可以看到和学习到我们的交流。

**Comment by runner365** [comment]
很想merge，最近修改了很多。
新增:
1，配置文件功能
配置application_name, streamname
2，动态push，pull功能
根据http命令来做push和pull
3，静态push功能
通过配置文件，静态push流到上游rtmp服务器；
我整理一下吧，然后再上传。

**Comment by gwuhaolin** [comment]
很强！我其实主要是做前端的，有空学习下go😅 所以还得靠你们这些老手指教。

**Comment by runner365** [comment]
alex-MacBook-Air:livego$ git branch
* branch_xiaoq
  master
alex-MacBook-Air:livego$ git push origin branch_xiaoq
remote: Permission to gwuhaolin/livego.git denied to runner365.
fatal: unable to access 'https://github.com/gwuhaolin/livego.git/': The requested URL returned error: 403
我本地的分支无法上传，没权限。

**Comment by c1ngular** [comment]
@runner365 我fork 了你的fork, 功能很实用！但是发现点问题， go run -race livego.go 的时候得到好几处提醒，包括 rtmp.go, stream.go, 貌似还有hls.go ，您有发现类似的情况吗？

**Comment by matthewgao** [comment]
> @runner365 我fork 了你的fork, 功能很实用！但是发现点问题， go run -race livego.go 的时候得到好几处提醒，包括 rtmp.go, stream.go, 貌似还有hls.go ，您有发现类似的情况吗？

我最近对性能做了很多改进单独rtmp的情况下已经优于nginx-rtmp-module， 可以试试最新版本
