### ISSUE TITLE
BUG报告，pool.go

### ISSUE THREAD

**Issue by fanr520** [gwuhaolin/livego#52]
livego/utils/pool/pool.go

const maxpoolsize = 500 * 1024

func (pool *Pool) Get(size int) []byte {
	if maxpoolsize-pool.pos < size {
		pool.pos = 0
		pool.buf = make([]byte, maxpoolsize)
	}
	b := pool.buf[pool.pos: pool.pos+size]
	pool.pos += size
	return b
}
当此函数的size 参数大于maxpoolsize 时，出现BUG挂机了。
代码修改如下
package pool

type Pool struct {
	pos int
	buf []byte
	max int
}

const maxpoolsize = 500 * 1024

func (pool *Pool) Get(size int) []byte {
	if (pool.pos+size)>pool.max{//长度过长
		pool.pos = 0
		if size>maxpoolsize{
			pool.max= size
		}else{
			pool.max= maxpoolsize
		}
		pool.buf = make([]byte, pool.max)	
	}
	b := pool.buf[pool.pos : pool.pos+size]
	pool.pos += size
	return b
}

func NewPool() *Pool {
	return &Pool{
		pos:0,
		max:maxpoolsize,
		buf: make([]byte, maxpoolsize),
	}
}

另有一个问题，这个maxpoolsize 大小是谁决定的RTMP报文最大好像只有65535为什么会越界呢？想不明白

**Comment by matthewgao** [comment]
maxpoolsize 和具体的报文大小没关系 就是想单纯的减少申请内存的次数，一次多申请一些, 另外这个问题已经fix
