### ISSUE TITLE
怎么运行livego服务呀？

### ISSUE THREAD

**Issue by dreamsline** [gwuhaolin/livego#54]
安装了最新版本的go，然后download zip.之后go build livego.go。不知道哪错了，没运行成功。下面是报错信息：
![kvA44H.png](https://s2.ax1x.com/2019/03/06/kvA44H.png)

**Comment by lystormenvoy** [comment]
一样的情况，无法编译

**Comment by dan2990** [comment]
me too

**Comment by bspider11** [comment]
我也是，能不能解释下

**Comment by bspider11** [comment]
@dreamsline @lystormenvoy @dan2990 搞定了，按照上面报错的目录把文件放进去就好了

**Comment by gwuhaolin** [comment]
已接入go mod，防止版本不一致导致的编译失败
