### ISSUE TITLE
HLS方式播放提示No publisher

### ISSUE THREAD

**Issue by MrNewWorld** [gwuhaolin/livego#57]
使用obs推流，使用rtmp和http-flv协议地址可以播放，但是hls不能播放，浏览器打开提示no publisher

**Comment by MrNewWorld** [comment]
解决了，推流名称必须固定为movie...

**Comment by vincentpham13** [comment]
> Solved, the name of the push stream must be fixed as movie...

push stream to rtmp://localhost:1935/movie/rfBd56ti2SMtYvSgD5xAV0YU99zampta7Z7S575KLkIZ9PYk
receive 127.0.0.1:7002/movie/movie.m3u8
is it correct? @callmejoo
