### ISSUE TITLE
 ReadFile .livego.json error:open .livego.json: no such file or directory

### ISSUE THREAD

**Issue by aute** [gwuhaolin/livego#74]
v:0.0.5

newtest docker run -p 1935:1935 -p 7001:7001 -p 7002:7002  --name livego gwuhaolin/livego
2019/11/04 08:56:28 main.go:118: start livego, version master
2019/11/04 08:56:28 liveconfig.go:35: starting load configure file(.livego.json)......
2019/11/04 08:56:28 liveconfig.go:38: ReadFile .livego.json error:open .livego.json: no such file or directory

**Comment by billytoe** [comment]
去 源码 里 下载  .livego.json 文件。

**Comment by everhopingandwaiting** [comment]
download the  .livego.json file , and copy this file to container  
`docker cp  .livego.json livego:/app`

it dosn`t work

**Comment by everhopingandwaiting** [comment]
> 去 源码 里 下载 .livego.json 文件。

下一步呢？

**Comment by everhopingandwaiting** [comment]
![image](https://user-images.githubusercontent.com/6021724/71613276-66778900-2be0-11ea-8154-59ff696777ce.png)

**Comment by nintha** [comment]
@everhopingandwaiting  试试这个 `docker cp .livego.json livego:/`

**Comment by ufukomer** [comment]
@nintha it does not work.

**Comment by taiji1985** [comment]
docker run -p 1935:1935 -p 7001:7001 -p 7002:7002  --name livego gwuhaolin/livego
2020/03/22 02:06:12 main.go:118: start livego, version master
2020/03/22 02:06:12 liveconfig.go:35: starting load configure file(.livego.json)......
2020/03/22 02:06:12 liveconfig.go:38: ReadFile .livego.json error:open .livego.json: no such file or directory

我也遇到同样的问题。
