### ISSUE TITLE
推流成功，但是hls  flv都不能播放，使用vlc也不能播放

### ISSUE THREAD

**Issue by wj2355021** [gwuhaolin/livego#92]
![1](https://user-images.githubusercontent.com/32793452/79408354-b2064500-7fcd-11ea-9c24-4c82e1a7b547.png)
![2](https://user-images.githubusercontent.com/32793452/79408359-b29edb80-7fcd-11ea-8ee9-4ea72411dadf.png)
![3](https://user-images.githubusercontent.com/32793452/79408362-b3d00880-7fcd-11ea-81f6-0c232bdeeea0.png)

**Comment by wj2355021** [comment]
已经解决 谢谢 我搞错了

**Comment by LOFTERART** [comment]
请问下如何解决的 也遇到了类似的问题
