### ISSUE TITLE
Module name

### ISSUE THREAD

**Issue by kravtsov-dima** [gwuhaolin/livego#99]
Guys, why does your module have a relative [name](https://github.com/gwuhaolin/livego/blob/master/go.mod#L1)? Why isn't it github.com/gwuhaolin/livego?

And why are imports on livego made relative?

This prevents me from using livego as a library. I can make a pool request if it's OK for you

**Comment by gwuhaolin** [comment]
yes, you can make a PR

**Comment by kravtsov-dima** [comment]
#100
